---
version: "3.7"

services:
  web:
    image: ansible/awx:${AWX_RELEASE}
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./resources/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./resources/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./resources/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./resources/awxcompose/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./resources/awxcompose/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    networks: 
      - 'awx'

  task:
    image: ansible/awx:${AWX_RELEASE}
    container_name: awx_task
    hostname: awx
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./resources/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./resources/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./resources/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./resources/awxcompose/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'
    networks: 
      - 'awx'

  redis:
    image: redis
    container_name: awx_redis
    hostname: awxredis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./resources/awxcompose/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "./resources/awxcompose/redis_socket:/var/run/redis/:rw"
    networks: 
      - 'awx'

  postgres:
    image: postgres:10
    container_name: awx_postgres
    hostname: awxprostgres
    restart: unless-stopped
    volumes:
      - "./resources/awxcompose/pgdocker/10/data/:/var/lib/postgresql/data:Z"
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      http_proxy: 
      https_proxy: 
      no_proxy: 
    networks: 
      - 'awx'

  gitea:
    image: gitea/gitea:${AWX_GITEA_RELEASE}
    container_name: awx_gitea
    hostname: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_DOMAIN=gitea
    restart: always
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "22:22"
    networks: 
      - 'awx'

  tools:
    build:
      context: .
      dockerfile: ./awxtools.dockerfile
    image: schneidermatic/${ARTIFACT_NAME_01}:${ARTIFACT_RELEASE_01}
    container_name: "awx_tools"
    hostname: awxtools
    volumes:
      - ./resources/docker/ssh-keys:/home/sysadm/.ssh/
    ports:
      - "2221:22"
    networks: 
      - 'awx'

  server1:
    build:
      context: .
    image: schneidermatic/${ARTIFACT_NAME_02}:${ARTIFACT_RELEASE_02}
    container_name: "server1"
    hostname: server1
    volumes:
      - ./resources/docker/ssh-keys:/home/sysadm/.ssh/
    ports:
      - "2222:22"
    networks: 
      - 'awx'

volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
  gitea-data:

networks:
  awx:
    driver: bridge
