---
version: '3.7'

services:
  web:
    image: ansible/awx:${AWX_RELEASE}
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./files/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./files/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./files/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./files/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./files/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy:
    networks: ['stack']

  task:
    image: ansible/awx:${AWX_RELEASE}
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./files/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./files/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./files/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./files/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'
    networks: ['stack']

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./files/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "./files/redis_socket:/var/run/redis/:rw"
    networks: ['stack']

  postgres:
    image: postgres:${AWX_POSTGRES_RELEASE}
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: 
      https_proxy: 
      no_proxy:
    networks: ['stack']

  gitea:
    image: gitea/gitea:${AWX_GITEA_RELEASE}
    container_name: awx_gitea
    hostname: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_DOMAIN=gitea
    restart: always
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "22:22"
    networks: ['stack']

networks: {stack:{}}

volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
  db-data:
  gitea-data:
